### PR TITLE
Translations update from Fedora Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Fedora Weblate](https://translate.fedoraproject.org) for [pykickstart/master](https://translate.fedoraproject.org/projects/pykickstart/master/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by bcl** [comment]
I don't see any actual translation in this commit.

**Comment by bcl** [comment]
@NorwayFun is there any reason to add a language without translations? The new Georgian file doesn't have anything new in it.

**Comment by NorwayFun** [comment]
@bcl  it will be there soon. Usually my translation memory handles most packages well, but this one is an exception. Will go through it manually and upload it shortly.
Sorry for inconvinience.

**Comment by bcl** [comment]
Thanks for the explanation!

**Pull request merged**
